language: python
python:
- "2.7"
# setup environment
env:
- DJANGO_VERSION=1.11.5
# install dependencies
install:
- pip install -r hola/requirements.txt

# run test scripts
script:
- python hola/manage.py test 