language: python
python:
- "2.7"
# setup environment
env:
- DJANGO_VERSION=1.11.5
# install dependencies
install:
- pip install -r Entregable 2/Web/requirements.txt
Entregable 2/Web/
# run test scripts
script:
- python Entregable 2/Web/manage.py test 