language: python
python:
- "3.6"
# setup environment
env:
- DJANGO_VERSION=1.11.5
# install dependencies
install:
- pip install -r Entregable_2/Web/requirements.txt

# run test scripts
script:
- python Entregable_2/Web/manage.py test 